name: visiting_card_app
description: A Flutter app to extract name, email & phone from visiting cards.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  http: ^1.2.2
  image_picker: ^1.1.2
  flutter_hooks: ^0.21.3+1
  flutter_image_compress: ^2.3.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  # Latest stable lints for Dart 3 & Flutter 3
  flutter_lints: ^6.0.0
